import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("Seeding Zaya Zen catalog...");

  // Clean old data
  await prisma.review.deleteMany();
  await prisma.orderItem.deleteMany();
  await prisma.order.deleteMany();
  await prisma.productVariant.deleteMany();
  await prisma.productImage.deleteMany();
  await prisma.product.deleteMany();
  await prisma.category.deleteMany();
  await prisma.banner.deleteMany();

  // 1. Categories
  const catDesigner = await prisma.category.create({
    data: {
      name: "Designer Panjabi",
      nameBn: "ডিজাইনার পাঞ্জাবি",
      slug: "designer-panjabi",
      description: "Exclusive hand-crafted embroidery and modern minimalist cuts for every special occasion.",
      sortOrder: 1,
    },
  });

  const catCotton = await prisma.category.create({
    data: {
      name: "Cotton & Casual Panjabi",
      nameBn: "সুতি ও ক্যাজুয়াল পাঞ্জাবি",
      slug: "cotton-casual",
      description: "Ultra-breathable 100% fine combed cotton designed for daily elegance and summer comfort.",
      sortOrder: 2,
    },
  });

  const catSemiFormal = await prisma.category.create({
    data: {
      name: "Semi-Formal Panjabi",
      nameBn: "সেমি ফরমাল পাঞ্জাবি",
      slug: "semi-formal",
      description: "Refined collar styling and subtle textures perfect for Jumu'ah, corporate ethnic days, and gatherings.",
      sortOrder: 3,
    },
  });

  const catPajama = await prisma.category.create({
    data: {
      name: "Pajama & Pants",
      nameBn: "পায়জামা ও প্যান্ট",
      slug: "pajama-pants",
      description: "Tailored Aligarh, Churidar, and straight trousers with comfortable waistbands.",
      sortOrder: 4,
    },
  });

  const catShirts = await prisma.category.create({
    data: {
      name: "Premium Shirts",
      nameBn: "প্রিমিয়াম শার্ট",
      slug: "shirts",
      description: "Fine yarn-dyed oxford and formal linen shirts tailored for sharp gentlemen.",
      sortOrder: 5,
    },
  });

  const categories = [catDesigner, catCotton, catSemiFormal, catPajama, catShirts];

  // 2. Demo Products (24 items)
  const productsData = [
    // Designer Panjabi
    {
      name: "Tradition & Modern Royal Cream Embroidered Panjabi",
      nameBn: "ট্রেডিশন অ্যান্ড মডার্ন রয়্যাল ক্রিম এমব্রয়ডারি পাঞ্জাবি",
      slug: "royal-cream-embroidered-panjabi",
      description: "The signature hero piece featured in our collection. Pure combed organic cotton in soothing royal cream with intricate hand-embroidered floral placket and mandarin collar. Tailored for festive prestige.",
      fabric: "100% Organic Combed Voile Cotton — Soft, breathable & lightweight",
      basePrice: 3650,
      salePrice: 2950,
      isClearance: true,
      categoryId: catDesigner.id,
      ratingAvg: 5.0,
      ratingCount: 64,
      imageUrl: "https://images.unsplash.com/photo-1597983073493-88cd35cf93b0?auto=format&fit=crop&q=80&w=800",
    },
    {
      name: "Zenith Royal Black Embroidered Panjabi",
      nameBn: "জেনিথ রয়্যাল ব্ল্যাক এমব্রয়ডারি পাঞ্জাবি",
      slug: "zenith-royal-black-embroidered",
      description: "Crafted with pure organic combed cotton featuring minimalist tone-on-tone neckline embroidery. Exudes timeless prestige.",
      fabric: "100% Fine Combed Cotton - Extremely soft & skin-friendly",
      basePrice: 3450,
      salePrice: 2850,
      isClearance: true,
      categoryId: catDesigner.id,
      ratingAvg: 4.9,
      ratingCount: 38,
      imageUrl: "https://images.unsplash.com/photo-1597983073493-88cd35cf93b0?auto=format&fit=crop&q=80&w=800",
    },
    {
      name: "Sultani Pure White Embroidered Festive Panjabi",
      nameBn: "সুলতানি পিওর হোয়াইট এমব্রয়ডারি ফেস্টিভ পাঞ্জাবি",
      slug: "sultani-pure-white-embroidered",
      description: "Crisp white base with subtle tone-on-tone ivory silk thread embroidery around the placket and cuffs. Epitome of regal purity.",
      fabric: "100% Giza Cotton with Silk Finish - Gentle luster",
      basePrice: 3850,
      salePrice: 3250,
      isClearance: false,
      categoryId: catDesigner.id,
      ratingAvg: 4.9,
      ratingCount: 42,
      imageUrl: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&q=80&w=800",
    },
    {
      name: "Nawabian Royal Maroon Zari Panjabi",
      nameBn: "নবাবিয়ান রয়্যাল মেরুন জরি পাঞ্জাবি",
      slug: "nawabian-royal-maroon-zari",
      description: "Exquisite deep crimson maroon fabric with delicate antique gold threadwork along the neckline. Ideal for weddings and evening celebrations.",
      fabric: "Fine Mercerized Cotton-Silk Blend - Opulent drape",
      basePrice: 4200,
      salePrice: 3450,
      isClearance: true,
      categoryId: catDesigner.id,
      ratingAvg: 5.0,
      ratingCount: 29,
      imageUrl: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&q=80&w=800",
    },
    {
      name: "Imperial Charcoal Hand-Stitched Panjabi",
      nameBn: "ইম্পেরিয়াল চারকোল হ্যান্ড-স্টিচড পাঞ্জাবি",
      slug: "imperial-charcoal-hand-stitched",
      description: "Deep charcoal tone accented with precise geometric hand stitches along the placket. Subtle sophistication.",
      fabric: "Luxury Blended Linen-Cotton - Breathable all-season weave",
      basePrice: 3800,
      salePrice: 3150,
      isClearance: false,
      categoryId: catDesigner.id,
      ratingAvg: 4.8,
      ratingCount: 24,
      imageUrl: "https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?auto=format&fit=crop&q=80&w=800",
    },
    {
      name: "Midnight Sapphire Jacquard Panjabi",
      nameBn: "মিডনাইট স্যাফায়ার জ্যাকার্ড পাঞ্জাবি",
      slug: "midnight-sapphire-jacquard",
      description: "Intricate all-over micro damask jacquard weave in deep sapphire blue. Shimmers gently in ambient light with pearl buttons.",
      fabric: "100% Jacquard Woven Cotton - Textured elegance",
      basePrice: 3500,
      salePrice: 2890,
      isClearance: true,
      categoryId: catDesigner.id,
      ratingAvg: 4.8,
      ratingCount: 33,
      imageUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=800",
    },
    {
      name: "Terracotta Mirage Festive Panjabi",
      nameBn: "টেরাকোটা মিরেজ ফেস্টিভ পাঞ্জাবি",
      slug: "terracotta-mirage-festive",
      description: "Signature Zaya Zen terracotta tint with understated pearl buttons and sleek mandarin collar.",
      fabric: "Giza Cotton with Silk Touch - Ultra soft finish",
      basePrice: 3600,
      salePrice: 2950,
      isClearance: true,
      categoryId: catDesigner.id,
      ratingAvg: 5.0,
      ratingCount: 42,
      imageUrl: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&q=80&w=800",
    },
    {
      name: "Midnight Indigo Zari Accent Panjabi",
      nameBn: "মিডনাইট ইন্ডিগো জরি অ্যাকসেন্ট পাঞ্জাবি",
      slug: "midnight-indigo-zari-accent",
      description: "Lustrous navy base with muted matte gold zari embroidery along collar and cuffs.",
      fabric: "Premium Viscose-Cotton Blend - Rich drape and comfort",
      basePrice: 4200,
      salePrice: 3600,
      isClearance: false,
      categoryId: catDesigner.id,
      ratingAvg: 4.9,
      ratingCount: 19,
      imageUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=800",
    },
    {
      name: "Onyx Shadow Minimalist Panjabi",
      nameBn: "অনিক্স শ্যাডো মিনিমালিস্ট পাঞ্জাবি",
      slug: "onyx-shadow-minimalist",
      description: "Jet black monochromatic design with concealed placket and hand-finished metallic buttons.",
      fabric: "100% Egyptian Cotton - Smooth feather-touch feel",
      basePrice: 3200,
      salePrice: 2650,
      isClearance: true,
      categoryId: catDesigner.id,
      ratingAvg: 4.7,
      ratingCount: 51,
      imageUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=800",
    },

    // Cotton & Casual Panjabi
    {
      name: "Pure Breeze Crisp White Cotton Panjabi",
      nameBn: "পিওর ব্রিজ ক্রিস্প হোয়াইট সুতি পাঞ্জাবি",
      slug: "pure-breeze-crisp-white-cotton",
      description: "The quintessential white Panjabi for Jumu'ah, morning prayers, and serene casual summer wear.",
      fabric: "100% Voile Combed Cotton - Extremely airy and light",
      basePrice: 2250,
      salePrice: 1850,
      isClearance: true,
      categoryId: catCotton.id,
      ratingAvg: 5.0,
      ratingCount: 88,
      imageUrl: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&q=80&w=800",
    },
    {
      name: "Emerald Green Handloom Cotton Panjabi",
      nameBn: "এমেরাল্ড গ্রিন হ্যান্ডলুম সুতি পাঞ্জাবি",
      slug: "emerald-green-handloom-cotton",
      description: "Rich jewel-tone emerald green woven on traditional Bengal handlooms with natural coconut shell buttons.",
      fabric: "100% Handloom Combed Cotton — Breathable & textured",
      basePrice: 2600,
      salePrice: 2150,
      isClearance: false,
      categoryId: catCotton.id,
      ratingAvg: 4.9,
      ratingCount: 36,
      imageUrl: "https://images.unsplash.com/photo-1597983073493-88cd35cf93b0?auto=format&fit=crop&q=80&w=800",
    },
    {
      name: "Dusty Rose Pastel Cotton Panjabi",
      nameBn: "ডাস্টি রোজ প্যাস্টেল সুতি পাঞ্জাবি",
      slug: "dusty-rose-pastel-cotton",
      description: "Soothing contemporary pastel dusty rose designed for daytime events, mehndi functions, and summer festivities.",
      fabric: "Pre-Washed Ultra-Soft Slub Cotton - Feather-light feel",
      basePrice: 2450,
      salePrice: 1950,
      isClearance: true,
      categoryId: catCotton.id,
      ratingAvg: 4.8,
      ratingCount: 29,
      imageUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&q=80&w=800",
    },
    {
      name: "Olive Moss Natural Cotton Panjabi",
      nameBn: "অলিভ মস ন্যাচারাল কটন পাঞ্জাবি",
      slug: "olive-moss-natural-cotton",
      description: "Earthy olive green with raw wooden buttons and comfortable relaxed silhouette.",
      fabric: "Slub Textured Pure Cotton - Soft natural texture",
      basePrice: 2400,
      salePrice: 1990,
      isClearance: false,
      categoryId: catCotton.id,
      ratingAvg: 4.8,
      ratingCount: 31,
      imageUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=800",
    },
    {
      name: "Desert Sand Daily Classic Panjabi",
      nameBn: "ডেজার্ট স্যান্ড ডেইলি ক্লাসিক পাঞ্জাবি",
      slug: "desert-sand-daily-classic",
      description: "Warm beige hue with tailored modern cut, side seam pockets, and breathable soft collar.",
      fabric: "100% Breathable Fine Cotton",
      basePrice: 2300,
      salePrice: 1890,
      isClearance: true,
      categoryId: catCotton.id,
      ratingAvg: 4.6,
      ratingCount: 27,
      imageUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&q=80&w=800",
    },
    {
      name: "Slate Blue Casual Slub Panjabi",
      nameBn: "স্লেট ব্লু ক্যাজুয়াল স্ল্যাব পাঞ্জাবি",
      slug: "slate-blue-casual-slub",
      description: "Subtle cross-weave slub cotton providing exceptional cooling in Bangladesh humidity.",
      fabric: "Pre-shrunk Fine Cotton - Extra soft wash",
      basePrice: 2500,
      salePrice: 2100,
      isClearance: false,
      categoryId: catCotton.id,
      ratingAvg: 4.9,
      ratingCount: 16,
      imageUrl: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&q=80&w=800",
    },
    {
      name: "Warm Ivory Jacquard Panjabi",
      nameBn: "ওয়ার্ম আইভরি জ্যাকার্ড পাঞ্জাবি",
      slug: "warm-ivory-jacquard",
      description: "Self-textured micro jacquard pattern that catches the sunlight with understated charm.",
      fabric: "100% Jacquard Woven Cotton",
      basePrice: 2700,
      salePrice: 2250,
      isClearance: true,
      categoryId: catCotton.id,
      ratingAvg: 4.8,
      ratingCount: 34,
      imageUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=800",
    },

    // Semi-Formal Panjabi
    {
      name: "Alabaster Ivory Minimalist Collar Panjabi",
      nameBn: "অ্যালাবাস্টার আইভরি মিনিমালিস্ট কলার পাঞ্জাবি",
      slug: "alabaster-ivory-minimalist-collar",
      description: "Light airy ivory shade with sharp structured collar and hidden snap buttons for modern gentlemen.",
      fabric: "Superfine Linen-Cotton Blend - Breathable luxury",
      basePrice: 2900,
      salePrice: 2400,
      isClearance: true,
      categoryId: catSemiFormal.id,
      ratingAvg: 4.9,
      ratingCount: 26,
      imageUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=800",
    },
    {
      name: "Elysian Ash Grey Semi-Formal Panjabi",
      nameBn: "এলিসিয়ান অ্যাশ গ্রে সেমি-ফরমাল পাঞ্জাবি",
      slug: "elysian-ash-grey-semi-formal",
      description: "Executive styling with stiffened band collar, tonal thread detailing, and sharp silhouette.",
      fabric: "Luxury Cotton Satin - Subtle sheen and soft hand feel",
      basePrice: 3100,
      salePrice: 2600,
      isClearance: false,
      categoryId: catSemiFormal.id,
      ratingAvg: 4.9,
      ratingCount: 22,
      imageUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=800",
    },
    {
      name: "Navy Meridian Placket Detail Panjabi",
      nameBn: "নেভি মেরিডিয়ান প্লাকেট ডিটেইল পাঞ্জাবি",
      slug: "navy-meridian-placket-detail",
      description: "Deep navy body complemented by micro-houndstooth inner placket and engraved horn buttons.",
      fabric: "Long-Staple Compact Cotton",
      basePrice: 3300,
      salePrice: 2750,
      isClearance: true,
      categoryId: catSemiFormal.id,
      ratingAvg: 4.8,
      ratingCount: 40,
      imageUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=800",
    },
    {
      name: "Mocha Brown Heritage Panjabi",
      nameBn: "মোচা ব্রাউন হেরিটেজ পাঞ্জাবি",
      slug: "mocha-brown-heritage",
      description: "Rich earth-tone mocha tailored with double-needle precision for evening social occasions.",
      fabric: "Polyester-Cotton Wrinkle-Resistant Blend",
      basePrice: 2900,
      salePrice: 2450,
      isClearance: false,
      categoryId: catSemiFormal.id,
      ratingAvg: 4.7,
      ratingCount: 15,
      imageUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=800",
    },
    {
      name: "Burgundy Velvet Collar Festive Panjabi",
      nameBn: "বার্গান্ডি ভেলভেট কলার ফেস্টিভ পাঞ্জাবি",
      slug: "burgundy-velvet-collar",
      description: "Deep wine tone with plush velvet inner band and matte gold hardware.",
      fabric: "Cotton-Silk Blend with Velvet Trims",
      basePrice: 3900,
      salePrice: 3200,
      isClearance: true,
      categoryId: catSemiFormal.id,
      ratingAvg: 5.0,
      ratingCount: 28,
      imageUrl: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&q=80&w=800",
    },

    // Pajama & Pants
    {
      name: "Classic Aligarh White Cotton Pajama",
      nameBn: "ক্লাসিক আলীগড় হোয়াইট সুতি পায়জামা",
      slug: "classic-aligarh-white-cotton-pajama",
      description: "Traditional wide leg Aligarh pajama with drawstring waist for supreme comfort.",
      fabric: "100% Soft Sheeting Cotton",
      basePrice: 950,
      salePrice: 790,
      isClearance: false,
      categoryId: catPajama.id,
      ratingAvg: 4.9,
      ratingCount: 65,
      imageUrl: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&q=80&w=800",
    },
    {
      name: "Tailored Slim Fit Straight Cut Pajama - White",
      nameBn: "টেইলর্ড স্লিম ফিট স্ট্রেইট কাট পায়জামা - হোয়াইট",
      slug: "tailored-slim-fit-straight-pajama-white",
      description: "Modern pant-style cut with functional zip fly, side pockets, and elasticated back waistband.",
      fabric: "Stretch Twill Cotton",
      basePrice: 1250,
      salePrice: 990,
      isClearance: true,
      categoryId: catPajama.id,
      ratingAvg: 4.8,
      ratingCount: 47,
      imageUrl: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&q=80&w=800",
    },
    {
      name: "Tailored Straight Cut Pajama - Jet Black",
      nameBn: "টেইলর্ড স্ট্রেইট কাট পায়জামা - জেট ব্ল্যাক",
      slug: "tailored-straight-pajama-black",
      description: "Pencil pant cut that pairs impeccably with light-toned and festive Panjabis.",
      fabric: "Fine Twill Mercerized Cotton",
      basePrice: 1300,
      salePrice: 1050,
      isClearance: false,
      categoryId: catPajama.id,
      ratingAvg: 4.9,
      ratingCount: 39,
      imageUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=800",
    },
    {
      name: "Traditional Churidar Pajama - Off White",
      nameBn: "ঐতিহ্যবাহী চুরিদার পায়জামা - অফ হোয়াইট",
      slug: "traditional-churidar-pajama-off-white",
      description: "Snug gathered ankle fit designed specifically for regal festive styling.",
      fabric: "Soft Voile Cotton",
      basePrice: 1100,
      salePrice: 890,
      isClearance: false,
      categoryId: catPajama.id,
      ratingAvg: 4.7,
      ratingCount: 18,
      imageUrl: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&q=80&w=800",
    },

    // Premium Shirts
    {
      name: "Executive Sky Blue Oxford Cotton Shirt",
      nameBn: "এক্সিকিউটিভ স্কাই ব্লু অক্সফোর্ড কটন শার্ট",
      slug: "executive-sky-blue-oxford-shirt",
      description: "Crisp button-down collar with fine basketweave texture. Ideal for both boardroom and dinner.",
      fabric: "100% Two-Ply Oxford Cotton",
      basePrice: 1950,
      salePrice: 1550,
      isClearance: true,
      categoryId: catShirts.id,
      ratingAvg: 4.9,
      ratingCount: 32,
      imageUrl: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&q=80&w=800",
    },
    {
      name: "Midnight Navy Linen-Cotton Casual Shirt",
      nameBn: "মিডনাইট নেভি লিনেন-কটন ক্যাজুয়াল শার্ট",
      slug: "midnight-navy-linen-cotton-shirt",
      description: "Airy linen weave washed for exceptional softness. Roll-tab sleeves and curved hem.",
      fabric: "55% French Linen, 45% Organic Cotton",
      basePrice: 2200,
      salePrice: 1790,
      isClearance: false,
      categoryId: catShirts.id,
      ratingAvg: 4.8,
      ratingCount: 26,
      imageUrl: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&q=80&w=800",
    },
    {
      name: "Pure White Formal Twill Shirt",
      nameBn: "পিওর হোয়াইট ফরমাল টুইল শার্ট",
      slug: "pure-white-formal-twill-shirt",
      description: "Wrinkle-resistant luxury twill with semi-spread collar and adjustable barrel cuffs.",
      fabric: "100% Compact Twill Cotton",
      basePrice: 2100,
      salePrice: 1690,
      isClearance: true,
      categoryId: catShirts.id,
      ratingAvg: 5.0,
      ratingCount: 45,
      imageUrl: "https://images.unsplash.com/photo-1620012253295-c15c429f66bf?auto=format&fit=crop&q=80&w=800",
    },
    {
      name: "Olive Khaki Mandarin Collar Casual Shirt",
      nameBn: "অলিভ খাকি ম্যান্ডারিন কলার ক্যাজুয়াল শার্ট",
      slug: "olive-khaki-mandarin-shirt",
      description: "Band collar shirt inspired by oriental tailoring, offering relaxed panache.",
      fabric: "100% Breathable Enzyme-Washed Cotton",
      basePrice: 1850,
      salePrice: 1490,
      isClearance: false,
      categoryId: catShirts.id,
      ratingAvg: 4.7,
      ratingCount: 19,
      imageUrl: "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&q=80&w=800",
    },
    {
      name: "Striped Metropolitan Business Shirt",
      nameBn: "স্ট্রাইপড মেট্রোপলিটান বিজনেস শার্ট",
      slug: "striped-metropolitan-business-shirt",
      description: "Classic Bengal blue and white stripes woven with high thread density.",
      fabric: "100% Egyptian Cotton",
      basePrice: 2350,
      salePrice: 1850,
      isClearance: true,
      categoryId: catShirts.id,
      ratingAvg: 4.8,
      ratingCount: 21,
      imageUrl: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&q=80&w=800",
    },
    {
      name: "Earthy Terracotta Linen Summer Shirt",
      nameBn: "আর্থি টেরাকোটা লিনেন সামার শার্ট",
      slug: "earthy-terracotta-linen-summer-shirt",
      description: "Signature terracotta linen shirt designed for sunset celebrations and coastal getaways.",
      fabric: "Pure Pre-Washed European Linen",
      basePrice: 2450,
      salePrice: 1950,
      isClearance: true,
      categoryId: catShirts.id,
      ratingAvg: 4.9,
      ratingCount: 33,
      imageUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=800",
    },
  ];

  for (const item of productsData) {
    const product = await prisma.product.create({
      data: {
        name: item.name,
        nameBn: item.nameBn,
        slug: item.slug,
        description: item.description,
        fabric: item.fabric,
        basePrice: item.basePrice,
        salePrice: item.salePrice,
        isClearance: item.isClearance,
        ratingAvg: item.ratingAvg,
        ratingCount: item.ratingCount,
        categoryId: item.categoryId,
        images: {
          create: [
            {
              url: item.imageUrl,
              alt: item.name,
              isPrimary: true,
              sortOrder: 0,
            },
          ],
        },
        variants: {
          create: [
            { size: "38", sku: `${item.slug}-38`, stock: 12 },
            { size: "40", sku: `${item.slug}-40`, stock: 20 },
            { size: "42", sku: `${item.slug}-42`, stock: 15 },
            { size: "44", sku: `${item.slug}-44`, stock: 8 },
          ],
        },
        reviews: {
          create: [
            {
              name: "Tanvir Ahmed",
              rating: 5,
              comment: "কাপড়টা সত্যি অনেক আরামদায়ক এবং সফট! ফিনিশিং আর কাটিং প্রিমিয়াম কোয়ালিটির। ডেলিভারিও দ্রুত পেয়েছি।",
              isVerified: true,
            },
            {
              name: "Rakibul Hasan",
              rating: 5,
              comment: "The color and fit are exactly as shown. Perfect for Eid and weddings. Highly recommend Zaya Zen!",
              isVerified: true,
            },
          ],
        },
      },
    });
    console.log(`Created product: ${product.name}`);
  }

  // 3. Demo Banners
  await prisma.banner.create({
    data: {
      title: "Wear Tradition, Your Way",
      subtitle: "Stock Clearance Offer — Save up to 40% on handcrafted designer Panjabis",
      imageUrl: "https://images.unsplash.com/photo-1597983073493-88cd35cf93b0?auto=format&fit=crop&q=80&w=1200",
      badge: "#স্টক_ক্লিয়ারেন্স_অফার",
      link: "/clearance",
      type: "HERO",
    },
  });

  console.log("Seeding finished successfully!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
